# ASP.NET Core


# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:


- task: SonarCloudPrepare@4
  inputs:
    SonarQube: 'Sonarcloud'
    organization: 'devops-jayasree'
    scannerMode: 'dotnet'
    projectKey: 'devops-jayasree_dotnetcorewebapi'
    projectName: 'dotnetcorewebapi'

- task: SonarQubeAnalyze@8
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

- task: SonarQubePublish@8
  inputs:
    pollingTimeoutSec: '300'

# - task: AdvancedSecurity-Codeql-Init@1
#   displayName: Initialize CodeQL
#   inputs:
# # build mode `none` is supported for C# but build mode `none` is NOT supported for Swift
# # so this pipeline definition will result in a failed run
#     languages: 'csharp'
#     buildtype: 'none'
 
- task: AdvancedSecurity-Codeql-Analyze@1
  displayName: Perform CodeQL Analysis
 
- task: AdvancedSecurity-Publish@1
  inputs:
    SarifsInputDirectory: '$(Build.SolutionDirectory)/.gdn/'